import type { Metadata } from "next";
import "./globals.css";
import Header from "./_views/layouts/header";
import Footer from "./_views/layouts/footer";
import { ToastContainer } from "react-toastify";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Toaster />

        {children}
        <Footer />
      </body>
    </html>
  );
}
